base:
  testdata:
    filepath_or_buffer: 'datasets/fake_data.csv'
    sep: '\t'
    skiprows: 1
    names: [ 'userId', 'itemId', 'rating', 'timestamp']
  data:
      filepath_or_buffer: 'datasets/ml-100k/u.data'
      sep: '\t'
      skiprows: 1
      names: [ 'userId', 'itemId', 'rating', 'timestamp']
  model:
    gmf:
      learning_rate: 0.01
      weight_decay: 0
      latent_dim: 100
      epochs: 10
      num_negative: 10
      batch_size: 512
      cuda: False
      optimizer: 'adam'
    als:
      learning_rate: 0.01
      latent_dim: 100
      epochs: 10
      reg_term: 0
    bpr:
      learning_rate: 0.01
      latent_dim: 100
      epochs: 10
      reg_term: 0
    emf:
      learning_rate: 0.01
      reg_term: 0.01
      exp_reg_term: 0.01
      latent_dim: 100
      epochs: 10
      momentum: 0.0
      weight_decay: 0.0
      batch_size: 512
      cuda: False
      optimizer: 'sgd'
      positive_threshold: 3
      nn: 10

