base:
  data:
    test:
      filepath_or_buffer: 'ratings.csv'
      sep: ','
      skiprows: 1
      names: [ 'userId', 'itemId', 'rating', 'timestamp']
      groups_filepath:
          - 'datasets/ml-100k/groupsWithHighRatings5.txt'
          - 'datasets/ml-100k/groupsWithModerateRatings5untested.txt'
    ml100k:
        filepath_or_buffer: 'datasets/ml-100k/u.data'
        sep: '\t'
        skiprows: 0
        names: [ 'userId', 'itemId', 'rating', 'timestamp']
    ml1m:
      filepath_or_buffer: 'datasets/ml-1m/ratings.dat'
      sep: '::'
      names: [ 'userId', 'itemId', 'rating', 'timestamp' ]
  model:
    gmf:
      learning_rate: 0.005
      weight_decay: 0.0000001
      latent_dim: 8
      epochs: 30
      num_negative: 10
      batch_size: 1024
      cuda: False
      optimizer_name: 'adam'
    mlp:
      learning_rate: 0.005
      weight_decay: 0.0000001
      latent_dim: 8
      epochs: 30
      num_negative: 10
      batch_size: 1024
      cuda: False
      optimizer_name: 'adam'
    als:
      learning_rate: 0.1
      latent_dim: 100
      epochs: 30
      reg_term: 0.001
    bpr:
      learning_rate: 0.01
      latent_dim: 100
      epochs: 10
      reg_term: 0.0
    emf:
      learning_rate: 0.01        # Mantido, bom ponto de partida
      reg_term: 0.01            # Aumentado para evitar overfitting
      expl_reg_term: 0.001      # Pequena regularização extra para estabilidade
      latent_dim: 50            # Reduzido para balancear complexidade e generalização
      epochs: 30                # Mantido, mas considere early stopping
      positive_threshold: 3     # Mantido, adequado para escala 1-5
      knn: 10                   # Mantido, suficiente para kNN inicial
    mf:
      learning_rate: 0.01
      reg_term: 0.001
      expl_reg_term: 0.0
      latent_dim: 80
      epochs: 10
      positive_threshold: 3
      knn: 10
    autoencoder:
      learning_rate: 0.005
      weight_decay: 0.0000001
      hidden_layer_features: 8
      epochs: 30
      cuda: False
      optimizer_name: 'adam'
      positive_threshold: 3
      knn: 10
      expl: true