name: Publish to PyPI

on:
  release:
    types: [created] # This workflow runs when a new release is created on GitHub

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is important for Trusted Publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # No need for username/password with Trusted Publishers